### ISSUE TITLE
Repository rename request

### ISSUE THREAD

**Issue by elir-copyleaks** [Copyleaks/moodle-plagiarism-checker#2]
We should rename the repository to the format:
moodle-{plugintype}_{pluginname} 
as specified in:
https://docs.moodle.org/dev/Plugin_contribution_checklist

So it should be:
moodle-plagiarism_copyleaks

**Comment by danmarsden** [comment]
can you please close this to signify that it has been completed?

**Comment by danmarsden** [comment]
..but you haven't renamed the repo yet? You still have 'checker' not copyleaks as the suffix?

**Comment by elir-copyleaks** [comment]
Renamed.
